### PR TITLE
update index.rst

### PR DESCRIPTION
**Pull request by robinacar**

### CODE REVIEW

**Review by martinh-dev — DISMISSED** [review]
Inital  commit for Price API

**Comment by martinh-dev** [comment]
Hi @vladimirhasko can you review the commit and merge it, if everything is fine. Or who is responsible for that?

**Comment by vladimirhasko** [comment]
> Hi @vladimirhasko can you review the commit and merge it, if everything is fine. Or who is responsible for that?

hi Martin,
as initially this document was defined to be API document and not UMN document please move the content to api-ref/source
otherwise jobs won't render the document properly.

**Review by martinh-dev — APPROVED** [review]
Changed from umn to api-ref

**Comment by martinh-dev** [comment]
Hi @vladimirhasko,

we updated it. Does it work this way?

**Comment by vladimirhasko** [comment]
> Hi @vladimirhasko,
> 
> we updated it. Does it work this way?

Yes and No.
Finally it tries to build the doc but fails on syntax RST errors.
Please have a look on these errors and fix syntax issues:

https://swift.eco.tsi-dev.otc-service.com/v1/AUTH_73733c21728443609ee0b47f64b5ce0b/zuul_logs/47d/5/5ba27938fd211d3bf48cb5e79b8869bb27cff860/check/otc-tox-docs/47dd3d6/tox/docs/3-commands%5B2%5D.log

**Comment by vladimirhasko** [comment]
@martinh-dev ,
if you want to use code-block: json you need to use strict json syntax without "..." strings otherwise it will break.
or rather use code-block: console if you don't want to follow strict json syntax

**Review by martinh-dev — APPROVED** [review]

**Comment by martinh-dev** [comment]
Hi @vladimirhasko,
the check was performed succesfull now. Can we move on?

**Comment by martinh-dev** [comment]
In the preview I can just see the empty price calcualtor page, but we want to show the API documentation. I can't se it in the preview. Is that possible?

**Comment by SebastianGode** [comment]
recheck

**Review by SebastianGode — APPROVED** [review]

**Pull request merged**
